#!/bin/sh
# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot; do
	alias $command="sudo $command"
done
unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura"

alias \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport"

alias \
	gt="${GOPATH}/src/github.com/baojiliu/test" \
	dsers="${GOPATH}/src/dsers.com" \
	api="${GOPATH}/src/dsers.com/dsers_api" \
	common="${GOPATH}/src/dsers.com/dsers_common" \
	shopify="${GOPATH}/src/dsers.com/shopify" \
	devops="${GOPATH}/src/dsers.com/devops" \
	flow="${GOPATH}/src/dsers.com/develop/flow" \
	dprohook="${GOPATH}/src/dsers.com/dpro-hook" \
	mi="${GOPATH}/src/dsers.com/mgnoberlo-core-api" \
	mj="${GOPATH}/src/dsers.com/mgnoberlo-core-job" \
	ev="vim $HOME/.config/nvim/init.vim" \
	devmysql="mycli -D dev" \
	af="apifox --force-device-scale-factor=1.7" \
	sp="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -" \
	wx="/opt/apps/com.qq.weixin.deepin/files/run.sh" \
	rt="QT_SCREEN_SCALE_FACTORS=2 robo3t" \
	sn='v ~/.config/nvim/plugged/vim-go/gosnippets/UltiSnips/go.snippets' \
	profile='v ~/.config/shell/profile && source ~/.config/shell/profile' \
	pb='cd $HOME/Sync/blog && git add . && git commit -m ":pencil:" && git push ' \
	np="new_post" \
	m4v="merge_mp4_videos" \
	pcp='git commit -m ":pencil:" && git push ' \

function replace_files() {
	find . \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i 's/$1/$2/g'
}
function merge_mp4_videos() {
	ffmpeg -f concat -safe 0 -i $1 -c copy $2
}
function new_post() {
	cd $HOME/Sync/blog/ && hugo new content/posts/$1.md && vim content/posts/$1.md
}
